import 'bootstrap/dist/css/bootstrap.min.css';
import './ontario-design-system/styles/ds-theme.css'
import './styles/globals.css'
import { Poppins } from 'next/font/google'
import Provider from './components/Provider';
import Header from './components/Header'
import Footer from './components/Footer'

const poppins = Poppins({weight: ['500', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={poppins.className} id='layout'>
          <Header/>

          <div id='content'>
            {children}
          </div>

          <div id='footer'>
            <Footer/>
          </div>
        </body>
      </Provider>
    </html>
  )
}
